### ISSUE TITLE
Make this repository public

### ISSUE THREAD

**Issue by afeld** [18F/product-guide#1]
Is there any reason not to?

**Comment by gbinal** [comment]
+1 

We work in the open by default.  :)

**Comment by afeld** [comment]
Oh sorry, just saw the disclaimer at the top of [the Google Doc](https://docs.google.com/document/d/1Jr_Bizbp4UjbINqglP86bElSWWI4XWrt7fVbFqlqNEM/edit). If links to Google Docs are the only reason for keeping this repository private, I have an idea for a workaround: https://github.com/18F/ideas/issues/8

**Comment by hollyallen** [comment]
Thanks folks, open by default! In addition to the links, which as @afeld points out will not actually even work for non-18f folks, there is potentially some non-public content as well. The content review to find non-public content is pending, so I made the repo private so at least @annahsebok could work on porting all the content from google docs to markdown files. Hopefully we can avoid all private non-link content, but we just aren't sure yet.

**Comment by annahsgraves** [comment]
Am working on this. Will be open and public very very soon.

**Comment by hollyallen** [comment]
All content reviewed, the whole guide will be public, repo now public.

**Comment by afeld** [comment]
:clap:

**Comment by annahsgraves** [comment]
:clap: :clap: Thanks @hollyallen!!!
