### ISSUE TITLE
GUIDE UPDATE - Suggested slack channels

### ISSUE THREAD

**Issue by annahsgraves** [18F/product-guide#11]
Parse each section for the slack channels mentioned in that section, then create quick reference list at top of bottom of page that calls out channels specific to that section.

**Comment by annahsgraves** [comment]
@mbland - If possible, I'd like to create a textbox off to the side or top of each page that has the various slack channels that are important for each section called out. Sort of a "quick reference" box on each page. Is that something you might be able to help me with with regards to markdown formatting, or perhaps you have a suggestion for a better way to approach this?

**Comment by mbland** [comment]
Yeah... I could imagine a front matter item like:

``` yaml
slack_channels:
- #product
- #hub
- #random
```

We can then update the template to post these with full links off to the side or the top or somewhere. cc: @andrewmaier

**Comment by annahsgraves** [comment]
:+1: !! Thanks for working with me on this. Let me know what I need to do to make this happen. Not really sure how might be best to format. A top section of the page? Off to the side (which I have no idea how to do in markdown)? 

What do y'all think @mbland @andrewmaier ?
