### ISSUE TITLE
GitHub documentation page on "Renewals and Handoffs" returns a 404

### ISSUE THREAD

**Issue by PabbyG** [18F/product-guide#113]
Steps to Reproduce:
1. USER go to https://handbook.18f.gov/github/
2. USER click on the "renewals & handoffs page in the 18F product guide" link
ERROR: SYSTEM returns 404 page for https://product-guide.18f.gov/lifecycle-of-a-project/renewals-and-handoffs/

**Comment by brentryanjohnson** [comment]
[This pull request](https://github.com/18F/handbook/pull/1844) fixes the broken links in the handbook page referred to here. Closing for now.
