### ISSUE TITLE
SECTION UPDATE (Project Comms) - Product storytellers

### ISSUE THREAD

**Issue by annahsgraves** [18F/product-guide#12]
Product storytellers are something we may be implementing to handle project communications. It has not been fully socialized yet, but if we move forward with it, we will want to add to and perhaps edit the Project Communications section of the guide to fold this in.

**Comment by annahsgraves** [comment]
Topic was announced in Product meeting. Should fold this in. Use [#outreach](https://18f.slack.com/archives/outreach) as primary source of communication on this topic. Outline of Product Storytellers is [here](https://docs.google.com/document/d/1BU3rrR1fX-vKPZuoApfk5c2MHiveyThyNEVeIKRvAqk/edit).

**Comment by annahsgraves** [comment]
@abisker would you be able to put in some time incorporating the new product storytellers outreach effort into the Project Comms section that you built?

**Comment by abisker** [comment]
@annahsebok sure thing, should be able to slot this in later this week or early next

**Comment by annahsgraves** [comment]
@abisker any progress?

**Comment by abisker** [comment]
@annahsebok - This text should be added directly after the current paragraph in the "Filling out a communications plan" portion of the Project Communications section.

Text:

Additionally, you need to designate a project “storyteller” who will give ongoing updates to the Comms team. This person does not have to be the product lead, and will serve as a conduit between the product and comms team. Notify the comms team of the storyteller contact in #outreach.

Every product must have:
- About.yml entry
- A comms plan
- Ideas for ~3 blog posts (from your team)

The comms team will work with the storyteller to ensure that the above items are accurate and up-to-date. The storyteller will also meet with the comms team for 5-10 minutes each week during the blog huddle to update the comms on the following:
- upcoming milestones and events (that you’re going to or could present at)
- any impending risks to prepare for press and mitigate any issues
- progress on comms plan / blog posts
- any other ways the comms team can help your project
- upcoming speaking events / conferences that the project/product is represented at
- any updates that need to be conveyed to the agency partner’s comms team (and who those people might be.)
- updates for 18F newsletter or Dolores or #news
- updates for open source community who might be able to help with ‘help-wanted’ tags

In the first meeting with the storyteller, the comms team will go over the blog mission and how we talk about our products. Future (very, very short) meetings will follow the template listed above.

**Comment by annahsgraves** [comment]
@abisker could you submit a PR for the guide with this text?

**Comment by abisker** [comment]
Sure! The Readme directs to file an issue so I did that instead. Will go to a PR.

**Comment by annahsgraves** [comment]
Ooo thanks! Will edit that.

**Comment by abisker** [comment]
Thanks! I might wait for that link then, want to make sure I'm getting it in the right place (still getting used to PRs for documents)
