### ISSUE TITLE
Links to Values in menu don't work (404)

### ISSUE THREAD

**Issue by smellems** [18F/product-guide#124]
All links under https://product-guide.18f.gov/values/ don't work.

The one I was looking for, was moved
https://product-guide.18f.gov/Values/working-in-the-open/

But in the menu it's lowercase and I get a 404
https://product-guide.18f.gov/values/working-in-the-open/

**Comment by michelle-rago** [comment]
@brentryanjohnson There are broken links on the Product Guide for everything under the values (second to last) section in the nav https://product-guide.18f.gov/future/strategy/. The directory is named "Values" and the links in prod go to "values". The above fix updated the link paths so I'm not sure why the updates aren't in prod. That being said, perhaps it's better to rename the directory to the lowercase. Thoughts?

**Comment by brentryanjohnson** [comment]
Looks like you're spot-on, @michelle-rago. The `_config.yml` configures the nav:
```
- text: Working in a way that reflects our values
  url: values/
```
It can't find that directory, presumably, as you noted, because of the cap.

**Comment by allisonnorman** [comment]
We're currently redoing the product guide and this is no longer a section in our v2 guide. Thanks for submitting it - we will be much more active in updating issues in the future.
