### ISSUE TITLE
404 for "Enable partner for long-term success" page 

### ISSUE THREAD

**Issue by SelenaJV** [18F/product-guide#126]
https://product-guide.18f.gov/we-help-our-partners-do-product-by-themselves/enable/ yields a 404 from side nav.

**Comment by nkkl** [comment]
This is linked from the front page, and candidates have started to ask me about it, so this should probably be addressed. 😛

**Comment by brandocalrissian** [comment]
Looks like the file referenced changed to [_/partners/enable/_](https://product-guide.18f.gov/partners/enable/) in [this commit](https://github.com/18F/product-guide/commit/2f1ccd23149e534f4be49ae1b91f1d95935e3e43#diff-dc398dd70e0b83e3b7c79d0a4b98dd0294313997520a89d2e9694b6b5e7797c1)

**Comment by allisonnorman** [comment]
This link is no longer on the site as we're updating _all the things_! Closing this issue as this specific link is no longer referenced on the front page.
