### ISSUE TITLE
Double check DAP and search.gov analytics configurations

### ISSUE THREAD

**Issue by allisonnorman** [18F/product-guide#150]
We should confirm the following are set up and continue to publish analytics data
- DAP (monitor and confirm)
- Search.gov (Get access to page, figure out reindexing strategy)

**Comment by allisonnorman** [comment]
DAP
- DAP metrics seem to be captured. We should double check after the next prod release.
- Should we send out an analytics report to a set of people on an ongoing basis? (Dashboard links are tough to share)

![Screen Shot 2021-01-28 at 10 54 00 AM](https://user-images.githubusercontent.com/6900926/106185031-28d48f00-6157-11eb-83ad-5a234c02d8fe.png)

**Comment by christophermather** [comment]
This can be considered complete with as part of the Guides consolidation work.
