### ISSUE TITLE
Incorporate feedback from Nina

### ISSUE THREAD

**Issue by allisonnorman** [18F/product-guide#151]
1. - [X] Nav: I think you'd be ok to get rid of the sub-sub nav that displays links to "Considerations", "Activities", etc.  Since it's the same for each subsection, and since the subsections are relatively short, it doesn't seem to add a ton of value and it clutters up the page.  Would def be happy to put this back in if users request it, tho.
2. - [X] Nav: I think this is baked in unfortunately, but it's kinda weird that you can't get back to each section's "overview" page from the side nav.
_**AN**: Added the overview sections to side nav_
3. - [X] "Deliver" overview: Please delete the first paragraph ("We try hard at 18F...").  It's redundant with another section.
4. - [X] "Collaborate and communicate": In the 2nd bullet under "Incorporation," hyperlink the phrase "Coach the partner," not just the word "partner."
5. - [X] "Measure success": In the first bullet under "Considerations," the 2nd sentence should actually be a separate bullet.
6. - [X] "Measure success": Remove "Resources" section.  This section wasn't ready.  (In fact, the entire Measure success content needs to be revisited, because the intro text is about transformation success, and the bullet points are all about measuring the product.  But that fix will be part of a different release.)
7. - [X] "Develop product leadership capacity": Under "Incorporation," hyperlink "Coach the product owner" to the "Coach the product owner" section of the Guide.
8. - [X] "Work with the vendor": Is this section intended to come before or after "Plan for the transition"?  It's after in the google doc, and before on the website.  It makes sense to me before, since the transition section talks about close out.
_AN: @ninamak We wanted feedback from you as this section was added during the holidays which is why it's after in the doc but I think it makes sense before "Plan for the transition" on the site._ 
9. - [X] "Work with the vendor": The 5th and 6th bullets under "Resources" are duplicates and should be deleted (the two "Vendor onboarding" links).
10. - [X] "Plan for the transition": In the last bullet under "Considerations," hyperlink "working with a vendor," not just "vendor."
11. - [X] "Plan for the transition": In the 2nd bullet under "Resources," hyperlinks are missing for "here" and "here."
12. - [X] I reviewed (and sometimes modified) the suggested edits in the google doc and those are good to incorporate.
13. - [X] For the Mural links (with one exception), I was able to create duplicates to add to the Project Resources workspace and lock these down to TTS-only.  The new links are in the "Mural Notes" section of the google doc.  I also updated them where they appear in the goole doc.
14. - [X] i also took a pass at ensuring consistency with the bullet points.  per the style guide, there are periods at the end of full sentences, and no periods otherwise.
15. - [X] Add locks for TTS-only Murals
16. - [X] Changes pushed to staging branch

**Comment by ninamak** [comment]
Re: #8: Great, so "Work with the Vendor" is where it should be on staging,
no movement needed.  As for my review of the content, I do think this
section could use a 2nd pass to generalize some of the content to a wider
variety of vendor scenarios (and to more clearly delineate between this
section and the transition section), but what's there is good material and
I don't think it makes sense to withhold it.  I created a sticky for this
on our planning mural.

---------------
Nina Mak
Product Manager
18F <https://18f.gsa.gov/> | GSA <http://www.gsa.gov/>
nina.mak@gsa.gov
C: 617-834-4596
Pronouns: she/her
