### ISSUE TITLE
SECTION UPDATE (Handoffs & Renewals) - What we do/don't support after

### ISSUE THREAD

**Issue by abisker** [18F/product-guide#16]
One other thing I think is missing here is explicit language around what we do and do NOT support during/after handoff that can be used to talk to partners --i.e., if 6 months down the line a something doesn't work, 18F doesn't troubleshoot because it's on cloud.gov, etc

**Comment by wslack** [comment]
Some language on this topic is here: https://pages.18f.gov/partnership-playbook/7-transfer-projects-back/

**Comment by annahsgraves** [comment]
@abisker we point to the partnership playbook a bunch of times. Is that not sufficient enough? 

CC: @brethauer @theresaanna (since this was their section)

**Comment by abisker** [comment]
@annahsebok I think the language in the playbook that @wslack linked to is great (https://pages.18f.gov/partnership-playbook/7-transfer-projects-back/), maybe something in this section should reference that directly? As in, make sure your partner is prepped and understands this?
