### ISSUE TITLE
Update product guide wiki

### ISSUE THREAD

**Issue by kmori** [18F/product-guide#170]
**Background**
_What should we consider when addressing this issue?_

**Acceptance criteria _(we'll know we're done when…)_** 
- [ ] 
- [ ] 

**Tasks**
- [ ] ...
- [ ] ...
- [ ]  PO review [if task involves content changes] 
- [ ]  Accessibility review [if needed]
- [ ]  Outreach approval [if needed]

**Comment by christophermather** [comment]
No longer needed now that Guides are consolidated.
