### ISSUE TITLE
Understand how 18F PMs are using the guide

### ISSUE THREAD

**Issue by kmori** [18F/product-guide#172]
**Background**
_What should we consider when addressing this issue?_

**Acceptance criteria _(we'll know we're done when…)_** 
- [ ] ...
- [ ] ...

**Tasks**
- [ ] ...
- [ ] ...
- [ ]  PO review [if task involves content changes] 
- [ ]  Accessibility review [if needed]
- [ ]  Outreach approval [if needed]

**Comment by christophermather** [comment]
Will be covered in future work on consolidated Guides.
