### ISSUE TITLE
UPDATE SECTION (Other Resources) - 18F Handbook link

### ISSUE THREAD

**Issue by annahsgraves** [18F/product-guide#20]
The link to the 18F Handbook in **Other Resources** is currently the github page. The Handbook itself will be live after it has been through the mgmt approval process. The link will need to be updated at that time.

**Comment by annahsgraves** [comment]
@melodykramer @andrewmaier ETA on when the handbook goes public?

**Comment by melodykramer** [comment]
It's going to be months and months away - I'll let you know when I know!

**Comment by melodykramer** [comment]
(And the url will not change if you use handbook.18f.gov as your URL.)

**Comment by annahsgraves** [comment]
Thanks @melodykramer. I've updated the link so we should be good. If there's no change that's going to happen in the future, I'll go ahead and close.
