### ISSUE TITLE
UPDATE SECTION (Project Comms) - Dashboard

### ISSUE THREAD

**Issue by annahsgraves** [18F/product-guide#22]
Additional guidance to come from @gboone re: how PMs should use the dashboard per comment in googledoc - 

@awfrancisco: Any additional guidance you want to add for how PMs should use the Dashboard?
@gboone: I am sure we will eventually but since we're up in the air on redesigning it ATM I'll hold off and update this when we have a real answer.

**Comment by gboone** [comment]
For now, PMs should either DM me or drop into the Dashboard channel on Slack. The dashboard we're going to create will likely use much of the same information but it'll probably have some we're not considering yet. It'll likely be some combination of information from the Team API, the rest of 18f.gsa.gov and other sources. Are we thinking we keep this an open conversation while we iterate on it?

**Comment by annahsgraves** [comment]
I'd like to keep this open so it's flagged for future iterations. Thanks @gboone

**Comment by annahsgraves** [comment]
Just confirmed that we point to [#dashboard](https://18f.slack.com/archives/dashboard) in the guide. Not going to mention @gboone explicitly since we don't list names in the guide to avoid going stale. Awaiting further details to come once it's been redesigned.
