### ISSUE TITLE
UPDATE SECTION (Project Comms) - Internal section linking

### ISSUE THREAD

**Issue by annahsgraves** [18F/product-guide#23]
Under developing a project comms plan within **Project Communications**, we need to link "distributed team" to the "Distributed Teamwork sub-section of **Your team (a.k.a. Staffing)**. Don't know how to do this in GH, so I'll need some help.

**Comment by annahsgraves** [comment]
@mbland is this something you could help me with?

**Comment by mbland** [comment]
Sure: `[distributed teamwork]({{ site.baseurl }}/lifecycle-of-a-project/staffing/#distributed-teamwork)`.

Thanks to @afeld in 18F/guides-style#37, the subsection anchor is already generated automatically. The `{{ site.baseurl }}` linking convention is explained in the Guides Template: https://pages.18f.gov/guides-template/add-a-new-page/#link-to-other-pages-within-the-guide.

**Comment by annahsgraves** [comment]
Bless you @mbland @afeld!
