### ISSUE TITLE
Project Storyteller Text

### ISSUE THREAD

**Issue by abisker** [18F/product-guide#46]
@annahsebok - This text should be added directly after the current paragraph in the "Filling out a communications plan" portion of the Project Communications section.

Text:

Additionally, you need to designate a project “storyteller” who will give ongoing updates to the Comms team. This person does not have to be the product lead, and will serve as a conduit between the product and comms team. Notify the comms team of the storyteller contact in #outreach.

Every product must have:
- About.yml entry
- A comms plan
- Ideas for ~3 blog posts (from your team)

The comms team will work with the storyteller to ensure that the above items are accurate and up-to-date. The storyteller will also meet with the comms team for 5-10 minutes each week during the blog huddle to update the comms on the following:
- upcoming milestones and events (that you’re going to or could present at)
- any impending risks to prepare for press and mitigate any issues
- progress on comms plan / blog posts
- any other ways the comms team can help your project
- upcoming speaking events / conferences that the project/product is represented at
- any updates that need to be conveyed to the agency partner’s comms team (and who those people might be.)
- updates for 18F newsletter or Dolores or #news
- updates for open source community who might be able to help with ‘help-wanted’ tags

In the first meeting with the storyteller, the comms team will go over the blog mission and how we talk about our products. Future (very, very short) meetings will follow the template listed above.

**Comment by annahsebok** [comment]
@abisker this issue needs to stay open until the edit is made. Could you fill an issue against the guide with this text?

**Comment by abisker** [comment]
I added this to the issue you started discussing this before (and then closed this)... that work?

**Comment by annahsgraves** [comment]
yup, just realized that!
