### ISSUE TITLE
Update description to include pages URL

### ISSUE THREAD

**Issue by melodykramer** [18F/product-guide#51]
The description for this repo contains a Google Doc.

**Comment by wslack** [comment]
Hey @melodykramer, I think the URL is there at the end, just hard to see.

For now, I removed the Google doc link https://docs.google.com/document/d/1Jr_Bizbp4UjbINqglP86bElSWWI4XWrt7fVbFqlqNEM/edit# as its depreciated, but will leave the final call on this issue to @rdpiazza and @annahsebok.

**Comment by annahsgraves** [comment]
@melodykramer is it a problem for us to link to a googledoc if the googledoc is still being used even if it's not public? We wanted to keep a link available to anybody working on this project internally. Contrary to what @wslack says, it is NOT depreciated.

**Comment by melodykramer** [comment]
That's fine - I would maybe move it from the header, though. We have a style guide preference for the pages link, which makes it easy for external folks to follow the link. (I was looking for the guide last night and didn't actually see it in the header...) Would it be possible to add to the top of the README?

**Comment by annahsgraves** [comment]
README has been edited to include the link. Thanks for the suggestion @melodykramer - had no clue what the best place was for that. Closing.
