### ISSUE TITLE
After you ship and Renewals & Handoffs not in nav

### ISSUE THREAD

**Issue by awfrancisco** [18F/product-guide#53]
They seem to be correct in _config.yml, but they don't appear in the drop down nav under Lifecycle of a Project in the live site.

**Comment by annahsgraves** [comment]
@awfrancisco are you sure? I'm on the live site right now and they are working just fine. You just have to scroll down the lifecycle list.

**Comment by awfrancisco** [comment]
Swear I scrolled, but now they seem to appear. Sorry for the false bug.

**Comment by annahsgraves** [comment]
No worries!
