### ISSUE TITLE
make /productguide work, not just /product-guide

### ISSUE THREAD

**Issue by annahsgraves** [18F/product-guide#6]
Make pages.18f.gov/productguide point to guide as well as pages.18f.gov/product-guide (which already does)

**Comment by gbinal** [comment]
@mbland - is there a good way to do this without creating a new repo?  If so, I'm game, but if not, I don't think it'll be worth the clutter of an entire repo in our github org just to serve as a redirect.

**Comment by annahsgraves** [comment]
thanks @gbinal. I know @hollyallen was looking around on this too...

**Comment by mbland** [comment]
Just created a 301 redirect from `/productguide` to `/product-guide`.

**Comment by annahsgraves** [comment]
Thanks @mbland! FYI @hollyallen
