### ISSUE TITLE
Document waffle.io vs. zenhub

### ISSUE THREAD

**Issue by noahmanger** [18F/product-guide#62]
So that product leads can choose the right tool for their team, document the pros and cons of Waffle.io and Zenhub.

**Comment by NoahKunin** [comment]
Can I ask that product go one step forward and pick one tool?

**Comment by annahsgraves** [comment]
@NoahKunin if you want to discuss this topic with the Product team and request that the Product team pick one tool, sure. However, the goal of this guide is to provide a **toolkit** that is comprehensive and speaks to the tools that work for a variety of different reasons on a variety of different kinds of projects with a variety of different kinds of teams. I'm hesitant to suggest that they are thus required to use one tool and one tool only.
