### ISSUE TITLE
Links for (1) "Guide to Distributed Teamwork" and (2) "this GitHub page" are broken/locked down

### ISSUE THREAD

**Issue by amcasari** [18F/product-guide#69]
Reference URl: https://pages.18f.gov/product-guide/lifecycle-of-a-project/staffing/

(1) Link to "Guide to..." requires access request (which is fine, if it is open)
(2) Link to "this GitHub page" gives a "this does not exist"...

**Comment by porta-antiporta** [comment]
@morningc thanks for the catch.
(1) is an private doc so only the 18F team can see it
(2) I submitted a PR, but in the meantime that page is part of our 18F handbook which was recently made public.  I've submitted a PR to correct, but in the meantime it is viewable at: https://handbook.18f.gov/distributed/

**Comment by rdpiazza** [comment]
I made a number of recent changes that fixed dead links. Between @porta-antiporta's changes and those, these appear to be addressed.
