### ISSUE TITLE
SECTION UPDATE (Renewals & handoffs) - Mandatory SME feedback

### ISSUE THREAD

**Issue by NoahKunin** [18F/product-guide#7]
We should start creating a mental dump list (if one isn't already out there) of what goes into a renewal or a hand off.

Dumping very rough notes so I don't forget, but we'll Google Doc this or something later:
- cloud.gov support plan
- who's running app level ops
- do they need a 3rd party app level ops contractor
- is HTTPS renewal set up correctly
- do they understand DNS cutover correctly

**Comment by annahsgraves** [comment]
@NoahKunin a reminder that you should feel free to submit a PR at anytime against this [here](https://pages.18f.gov/product-guide/lifecycle-of-a-project/renewals-and-handoffs/).

FYI - [slack convo for background](https://18f.slack.com/archives/product/p1452783293000008)
