### ISSUE TITLE
Link to "View or save all the cards (PDF)" is broken [404 error]

### ISSUE THREAD

**Issue by amcasari** [18F/product-guide#70]
Ref URI: https://pages.18f.gov/product-guide/lifecycle-of-a-project/design-and-development/

Looking for "Design Method Cards" leads to this link:

https://methods.18f.gov/assets/downloads/18F-Method-Cards-beta-Preview.pdf

which gives a 404 error.

**Comment by annahsgraves** [comment]
@rdpiazza FYI

**Comment by porta-antiporta** [comment]
Thanks for the catch!  I've created a PR to remove the outdated links.  To download the method cards you can go to methods.18f.gov (linked on the ref URI as well).
