### ISSUE TITLE
transfer ownership of product guide

### ISSUE THREAD

**Issue by annahsgraves** [18F/product-guide#71]
Since I'm not on the product team anymore, I'm thinking the ownership of this guide should be transferred. Thoughts @rdpiazza?

**Comment by annahsgraves** [comment]
fyi @rdpiazza @porta-antiporta I'm going to unwatch this guide so I no longer get notifications. Feel free to transfer ownership as you see fit!

**Comment by rdpiazza** [comment]
Turns out the right solution was to make me an admin and not to transfer ownership, which has been done.
