### ISSUE TITLE
Link to "How 18F Manages Client Accounts" appears outdated

### ISSUE THREAD

**Issue by mheadd** [18F/product-guide#75]
Reference URI: https://pages.18f.gov/product-guide/what-is-a-product-lead/

The link "How 18F Manages Client Accounts" points to a Google Doc, but the doc indicates that the content has been ported over to the [18F Handbook](https://handbook.18f.gov/client-accounts/). Wondering if the link should be updated to point directly to the relevant page in the handbook.

**Comment by porta-antiporta** [comment]
thx @mheadd!  submitted #76 to fix. if u have a few cycles, pls review and merge.
